export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const NO_ARTICLES = 'NO_ARTICLES';
export const GET_ALL_ARTICLES_LOADING = 'GET_ALL_ARTICLES_LOADING';
export const GET_ALL_ARTICLES_ERROR = 'GET_ALL_ARTICLES';
